version: "3.9"
services:
  db:
    image: ankane/pgvector
    container_name: local-alloydb
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: secondbrain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
